

def get_continent_for_country(country_name):
    country_to_continent = {
        'Afganistan': 'Azja',
        'Albania': 'Europa',
        'Algieria': 'Afryka',
        'Andora': 'Europa',
        'Angola': 'Afryka',
        'Antigua i Barbuda': 'Ameryka',
        'Arabia Saudyjska': 'Azja',
        'Argentyna': 'Ameryka',
        'Armenia': 'Azja',
        'Aruba': 'Ameryka',
        'Australia': 'Australia',
        'Austria': 'Europa',
        'Azerbejdżan': 'Azja',
        'Bahamy': 'Ameryka',
        'Bahrajn': 'Azja',
        'Bangladesz': 'Azja',
        'Barbados': 'Ameryka',
        'Belgia': 'Europa',
        'Belize': 'Ameryka',
        'Benin': 'Afryka',
        'Bermudy': 'Ameryka',
        'Bhutan': 'Azja',
        'Boliwia': 'Ameryka',
        'Bośnia i Hercegowina': 'Europa',
        'Botswana': 'Afryka',
        'Brazylia': 'Ameryka',
        'Brunei': 'Azja',
        'Brytyjskie Wyspy Dziewicze': 'Ameryka',
        'Bułgaria': 'Europa',
        'Burkina Faso': 'Afryka',
        'Burundi': 'Afryka',
        'Chile': 'Ameryka',
        'Chiny': 'Azja',
        'Tajwan': 'Azja',
        'Chorwacja': 'Europa',
        'Cypr': 'Azja',
        'Czad': 'Afryka',
        'Czarnogóra': 'Europa',
        'Czechy': 'Europa',
        'Dania': 'Europa',
        'Demokratyczna Republika Konga': 'Afryka',
        'Dominika': 'Ameryka',
        'Dominikana': 'Ameryka',
        'Dżibuti': 'Afryka',
        'Egipt': 'Afryka',
        'Ekwador': 'Ameryka',
        'Erytrea': 'Afryka',
        'Estonia': 'Europa',
        'Eswatini': 'Afryka',
        'Etiopia': 'Afryka',
        'Fidżi': 'Australia',
        'Filipiny': 'Azja',
        'Finlandia': 'Europa',
        'Francja': 'Europa',
        'Gabon': 'Afryka',
        'Gambia': 'Afryka',
        'Ghana': 'Afryka',
        'Grecja': 'Europa',
        'Grenada': 'Ameryka',
        'Gruzja': 'Azja',
        'Guam': 'Ameryka',
        'Gujana': 'Ameryka',
        'Gwatemala': 'Ameryka',
        'Gwinea': 'Afryka',
        'Gwinea Bissau': 'Afryka',
        'Gwinea Równikowa': 'Afryka',
        'Haiti': 'Ameryka',
        'Hiszpania': 'Europa',
        'Holandia': 'Europa',
        'Honduras': 'Ameryka',
        'Hongkong': 'Azja',
        'Indie': 'Azja',
        'Indonezja': 'Azja',
        'Indywidualni sportowcy neutralni': 'Neutralni',
        'Irak': 'Azja',
        'Iran': 'Azja',
        'Irlandia': 'Europa',
        'Islandia': 'Europa',
        'Izrael': 'Azja',
        'Jamajka': 'Ameryka',
        'Japonia': 'Azja',
        'Jemen': 'Azja',
        'Jordania': 'Azja',
        'Kajmany': 'Ameryka',
        'Kambodża': 'Azja',
        'Kamerun': 'Afryka',
        'Kanada': 'Ameryka',
        'Katar': 'Azja',
        'Kazachstan': 'Azja',
        'Kenia': 'Afryka',
        'Kirgistan': 'Azja',
        'Kiribati': 'Australia',
        'Kolumbia': 'Ameryka',
        'Komory': 'Afryka',
        'Kongo': 'Afryka',
        'Kosowo': 'Europa',
        'Kostaryka': 'Ameryka',
        'Korea Południowa': 'Azja',
        'Korea Północna': 'Azja',
        'Kuba': 'Ameryka',
        'Kuwejt': 'Azja',
        'Laos': 'Azja',
        'Lesotho': 'Afryka',
        'Liban': 'Azja',
        'Liberia': 'Afryka',
        'Libia': 'Afryka',
        'Liechtenstein': 'Europa',
        'Litwa': 'Europa',
        'Luksemburg': 'Europa',
        'Łotwa': 'Europa',
        'Madagaskar': 'Afryka',
        'Malawi': 'Afryka',
        'Malediwy': 'Azja',
        'Malezja': 'Azja',
        'Mali': 'Afryka',
        'Malta': 'Europa',
        'Maroko': 'Afryka',
        'Mauretania': 'Afryka',
        'Mauritius': 'Afryka',
        'Meksyk': 'Ameryka',
        'Mikronezja': 'Australia',
        'Mjanma': 'Azja',
        'Mołdawia': 'Europa',
        'Monako': 'Europa',
        'Mongolia': 'Azja',
        'Mozambik': 'Afryka',
        'Namibia': 'Afryka',
        'Nauru': 'Australia',
        'Nepal': 'Azja',
        'Niemcy': 'Europa',
        'Niger': 'Afryka',
        'Nigeria': 'Afryka',
        'Nikaragua': 'Ameryka',
        'Norwegia': 'Europa',
        'Nowa Zelandia': 'Australia',
        'Macedonia Północna': 'Europa',
        'Olimpijska reprezentacja uchodźców': 'Neutralni',
        'Oman': 'Azja',
        'Pakistan': 'Azja',
        'Palau': 'Australia',
        'Palestyna': 'Azja',
        'Panama': 'Ameryka',
        'Papua-Nowa Gwinea': 'Australia',
        'Paragwaj': 'Ameryka',
        'Peru': 'Ameryka',
        'Polska': 'Europa',
        'RPA': 'Afryka',
        'Portoryko': 'Ameryka',
        'Portugalia': 'Europa',
        'Republika Środkowoafrykańska': 'Afryka',
        'Republika Zielonego Przylądka': 'Afryka',
        'Rumunia': 'Europa',
        'Rwanda': 'Afryka',
        'Saint Kitts i Nevis': 'Ameryka',
        'Saint Lucia': 'Ameryka',
        'Saint Vincent i Grenadyny': 'Ameryka',
        'Salwador': 'Ameryka',
        'Samoa': 'Australia',
        'Samoa Amerykańskie': 'Australia',
        'San Marino': 'Europa',
        'Senegal': 'Afryka',
        'Serbia': 'Europa',
        'Seszele': 'Afryka',
        'Sierra Leone': 'Afryka',
        'Singapur': 'Azja',
        'Słowacja': 'Europa',
        'Słowenia': 'Europa',
        'Somalia': 'Afryka',
        'Sri Lanka': 'Azja',
        'USA': 'Ameryka',
        'Sudan': 'Afryka',
        'Sudan Południowy': 'Afryka',
        'Surinam': 'Ameryka',
        'Syria': 'Azja',
        'Szwajcaria': 'Europa',
        'Szwecja': 'Europa',
        'Tadżykistan': 'Azja',
        'Tajlandia': 'Azja',
        'Tanzania': 'Afryka',
        'Timor Wschodni': 'Azja',
        'Togo': 'Afryka',
        'Tonga': 'Australia',
        'Trynidad i Tobago': 'Ameryka',
        'Tunezja': 'Afryka',
        'Turcja': 'Azja',
        'Turkmenistan': 'Azja',
        'Tuvalu': 'Australia',
        'Uganda': 'Afryka',
        'Ukraina': 'Europa',
        'Urugwaj': 'Ameryka',
        'Uzbekistan': 'Azja',
        'Vanuatu': 'Australia',
        'Wenezuela': 'Ameryka',
        'Węgry': 'Europa',
        'Wielka Brytania': 'Europa',
        'Wietnam': 'Azja',
        'Włochy': 'Europa',
        'Wybrzeże Kości Słoniowej': 'Afryka',
        'Wyspy Cooka': 'Australia',
        'Wyspy Dziewicze Stanów Zjednoczonych': 'Ameryka',
        'Wyspy Marshalla': 'Australia',
        'Wyspy Salomona': 'Australia',
        'Wyspy Świętego Tomasza i Książęca': 'Afryka',
        'Zambia': 'Afryka',
        'Zimbabwe': 'Afryka',
        'Zjednoczone Emiraty Arabskie': 'Azja'
    }

    return country_to_continent.get(country_name, 'Nieznany kontynent')